### ISSUE TITLE
Single spectrum instead of three spectra

### ISSUE THREAD

**Issue by weaverba137** [sbailey/prospect#12]
Another request from the recent visual inspection session at the DESI-UK meeting was to be able to switch back and forth between a single spectrum with all spectrograph arms coadded together and the current individual spectrograph arms view.  Additionally, in the individual spectrograph arms view, be able to turn arms on and off individually.

* More people seem to be used to the idea of a single spectrum, similar to how SDSS displays spectra, even though SDSS has two spectrograph arms.
* Some features fall right on the overlap between two arms, and they can be really hard to see there.
* The alternative is to train people to accept that the individual spectrograph view is qualitatively better than a single, unbroken spectrum.

**Comment by armengau** [comment]
Done. In current implementation:

- can switch back and forth single arm / coadd
- default is coadd. However, even in coadd mode the single arm spectra are visible with a small alpha=0.2, so that VIs don't forget them.
- feature to turn on/off arms individually : not implemented, I'm not sure it is useful.

Technical points:
- Could not use the desispec.coaddition.coadd_cameras() since this function a) also coadds individual exposures and b) assumes wavelength grids are aligned.
- Anyway in order to avoid overloading the html pages, coaddition is mainly done inside the CustomJS code, directly from smoothed spectra and noises.
