### ISSUE TITLE
fix multiple spectra per object

### ISSUE THREAD

**Issue by sbailey** [sbailey/prospect#2]
Prospect currently doesn't work if there are multiple spectra per object (!).  Fix that, e.g. by doing a coadd on-the-fly.

**Comment by weaverba137** [comment]
I think I just hit this bug.  Is this related to
```python
nspec = spectra.num_spectra() 
assert len(zbest) == nspec
```

**Comment by weaverba137** [comment]
In `create_model()`, I don't think it is at all necessary that `len(zbest) == nspec`.  From what I can tell, all of the methods on the `spectra` object return scalars or arrays with the same length as `zbest`.

**Comment by weaverba137** [comment]
This is where it's a bit more serious:
```python
assert np.all(zcatalog['TARGETID'] == spectra.fibermap['TARGETID'])
```

**Comment by armengau** [comment]
This issue of having prospect work with multiple spectra per target is still unsettled (when we don't want to see coadds in the viewer).
I had commented the "magic sequence" :  ii = np.argsort(np.argsort(targetids)) ;  jj = np.argsort(zcatalog['TARGETID']) ;  kk = jj[ii] ; zcatalog = zcatalog[kk]

and used plotspectra() by requiring that the input zbest matches the input spectra - which was probably an expedient. @sbailey uncommented these lines, what was the reason for that ?

Anyway the following two lines after the "magic sequence" can't be ok at the same time :
        assert np.all(zcatalog['TARGETID'] == targetids)
        assert np.all(zcatalog['TARGETID'] == spectra.fibermap['TARGETID'])
since spectra.targetids() is different from fibermap['TARGETID'] if multiple spectra per target

**Comment by sbailey** [comment]
That magic sequence of argsorts rearranges the zcatalog to have `zcatalog['TARGETID']` be in the same order as the input `targetids` array, without requiring either to be sorted by `targetid` or any other specific ordering.

But, that only works if both have the same targetids and they are unique, i.e. no double entries for multiple exposures of the same targets.  I think that works fine if the reshuffling is done after the coadding, but it isn't intended to work for individual exposures where the same targetid could appear multiple times.

I haven't thought deeply about how we should handle that case, other than coadding for now.

**Comment by armengau** [comment]
Ok, so what if, in place of these argsorts, we use the function below ?
I have to check explicitely but
- it should do exactly the same if zcatalog / targetids have random ordering but same and unique targetids
- it still works if there are several single exposure per target
- it takes cpu certainly, I will check if this is a negligeable cpu wrt the rest of the code...


```
def match_zcat_to_spectra(zcat_in,spectra) :
    '''
    zcat_in : Table from redshift fitter
    creates a new Table with rows matched to the targetids of input spectra
    '''
    zcat_out = Table(dtype=zcat_in.dtype)
    for i_spec in range(spectra.num_spectra()) :
        ww, = np.where((zcat_in['TARGETID'] == spectra.fibermap['TARGETID'][i_spec]))
        if len(ww)!=1 : raise RuntimeError("issue with zcat table!")
        zcat_out.add_row(zcat_in[ww[0]])
    return zcat_out
```
